### ISSUE TITLE
Domain is missing in generated sitemap

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para-seo_tools#6]
I get URLs without domain name

``` xml
  <url>
    <loc>http:///</loc>
  </url>
```

**Comment by vala** [comment]
Is configuring the app's host name of any help ?

Documented with https://github.com/para-cms/seo_tools-para/commit/fa807e246147244468c98ccbb8b8fa5c2c04e2bd

**Comment by gabriel-cardoso** [comment]
Yes indeed !

**Comment by vala** [comment]
we should raise an error if it's not configured !
